### PR TITLE
peercoin testnet object

### PR DESCRIPTION
**Pull request by peerchemist**

### CODE REVIEW

**Comment by bananenwilly** [comment]
I think dart dislikes variables with dashes

**Comment by peerchemist** [comment]
What about this?

**Comment by bananenwilly** [comment]
Surprised the linter didn't complain. This is valid now but camelCase is usually enforced

**Comment by peerchemist** [comment]
I'm pythonista, camel case is sacrilege for us.

**Review by bananenwilly — APPROVED** [review]

**Pull request merged**
